function Why() {
	return (
		<div className="why" id="why">
			<h2 className="why-head">
				Why <span>BeQuest?</span>
			</h2>

			<p className="why-p">
				IN REAL LIFE YOU HAVE ASSETS LIKE HOME. THEY CAN'T GET LOST OR EVEN
				AFTER A PERSON DIES THERI ASSETS TRANSFER TO THEIR NEXT HIER OR
				INHERITOR RIGHT? YEAH..! SO WHY NOT THE SAME WITH DIGITAL ASSETS LIKE
				COIN, TOKEN, NFT WHICH EVEN WORTH SO MUCH. MOST TIMES WHEN A PERSON DIES
				OR MISPLACES HIS PRIVATE KEY, HIS CRYPTOCURRENCIES ARE LOST FOREVER ON
				THE BLOCKCHAIN AND OVER $10 BILLION WORTH OF BITCOIN ALONE HAS BEEN LOST
				DUE TO THIS.
			</p>

			<p className="why-p">
				BEQUEST ALLOWS YOU TO TRANSFER YOUR ASSETS TO YOUR HEIR IN A
				DECENTRALIZED MANNER. YOU SIGN THE LEGACY BY PROVIDING NEXT INHERITOR
				DETAILS LIKE WALLET ADDRESS AND SET A TIME ON WHICH YOU WANT TO EXCUTE
				YOUR LEGACY REQUEST.
			</p>
		</div>
	);
}

export default Why;
